#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.cm as cm
cmap = cm.seismic

f = np.genfromtxt(sys.argv[1])
print f.shape
plt.imshow(f[::-1,:],cmap=cmap)
data = f
plt.savefig("/tmp/fig.png")
plt.show()